export const INVESTMENT_RULES = [
  { id: 1, category: "매수 원칙", rule: "1등 기업만 사라", detail: "해당 섹터 1위 기업만 투자 대상으로 삼는다", icon: "🏆" },
  { id: 2, category: "매수 원칙", rule: "1등 기업은 악재가 나오면 기회다", detail: "시장 선도 기업의 악재는 매수 기회로 활용", icon: "📉" },
  { id: 3, category: "매수 타이밍", rule: "떨어지는 날 주식을 사라, 처음에는 300만원", detail: "하락일에 분할 매수 시작, 첫 매수는 300만원 이하", icon: "💰" },
  { id: 4, category: "매수 금지", rule: "오르는 날 떨어지는 주식 사지 마라", detail: "시장이 전반적으로 오르는데 혼자 떨어지는 종목은 피한다", icon: "🚫" },
  { id: 5, category: "매수 금지", rule: "목표가 하향 시 현재가 20% 빠질 때까지 사지 마라", detail: "애널리스트 목표가 하향 후 20% 하락 전까지는 매수 자제", icon: "⚠️" },
  { id: 6, category: "매수 금지", rule: "휴가날 오전에 사지 마라", detail: "휴가 기간 오전은 거래 회피", icon: "🏖️" },
  { id: 7, category: "매수 금지", rule: "10시 30분 전 주식은 가짜", detail: "장 시작 후 10:30 이전 가격은 신뢰하지 마라", icon: "⏰" },
  { id: 8, category: "매수 금지", rule: "명절 주에는 사지 마라", detail: "연휴 전후 주간은 매수 자제", icon: "🎊" },
  { id: 9, category: "매수 금지", rule: "다 오르는데 떨어지는 주식 사지 마라", detail: "전체 시장 상승 시 홀로 하락하는 종목은 피한다", icon: "📊" },
  { id: 10, category: "매수 금지", rule: "오르는 섹터에서 떨어지는 주식 사지 마라", detail: "상승 섹터 내 약세 종목은 문제가 있다는 신호", icon: "🔻" },
  { id: 11, category: "매수 금지", rule: "적자난 회사 주식 싸다고 사지 마라", detail: "영업적자 기업은 저가라도 매수 금지", icon: "💸" },
  { id: 12, category: "매수 금지", rule: "유튜브에서 오른다고 하는 주식은 팔아라", detail: "SNS/유튜브 추천 종목은 이미 고점일 가능성 높음", icon: "📺" },
  { id: 13, category: "계절 주의", rule: "장마기간 투자 조심 (장마 끝 후 매수)", detail: "6-7월 장마기간은 투자를 자제하고 장마 종료 후 재진입", icon: "🌧️" },
  { id: 14, category: "매도 원칙", rule: "목표가 하향 종목 주의 (탈출 전략)", detail: "목표가 하향 시 즉시 매도 전략 수립", icon: "🏃" },
  { id: 15, category: "매도 원칙", rule: "목표가 낮추면 50% 떨어진다, 무조건 판다", detail: "목표가 하향 시 주가가 50% 하락할 수 있으므로 즉시 매도", icon: "🔥" },
  { id: 16, category: "매도 원칙", rule: "유튜브 오른다고 하는 주식은 팔아라", detail: "미디어 노출이 많아지면 이미 고점 신호", icon: "📡" },
  { id: 17, category: "종목 선정", rule: "거래량이 많은 주식을 사라", detail: "일평균 거래량이 충분한 종목만 투자 대상", icon: "📈" },
  { id: 18, category: "종목 선정", rule: "배당이 있는 주식을 사라", detail: "배당을 지급하는 기업은 재무 건전성의 증거", icon: "💎" },
  { id: 19, category: "종목 선정", rule: "회장 나이 많고 후계구도 있으면서 실적 내는 주식", detail: "세대교체 이슈가 있으나 실적을 내는 기업은 기회", icon: "👴" },
  { id: 20, category: "종목 선정", rule: "배당 안 하는 회사 사지 마라", detail: "무배당 기업은 투자 제외", icon: "❌" },
  { id: 21, category: "종목 선정", rule: "거래량 없는 회사 사지 마라", detail: "거래량 부족 종목은 유동성 위험", icon: "🚷" },
  { id: 22, category: "기타", rule: "주식 분석 필수, 대외환경 변화 감지 필수", detail: "글로벌 경제 변화, 금리, 환율, 지정학적 리스크 반드시 체크", icon: "🌍" },
];

export const PORTFOLIO_DATA = [
  {
    ticker: "005670",
    name: "NICE",
    shares: 12776,
    evalAmount: 154334080,
    profit: -26928899,
    profitRate: -14.86,
    avgPrice: 14200,
    currentPrice: 12080,
  },
  {
    ticker: "302440",
    name: "SK바이오사이언스",
    shares: 2016,
    evalAmount: 82454400,
    profit: -20945989,
    profitRate: -20.26,
    avgPrice: 51200,
    currentPrice: 40900,
  },
  {
    ticker: "009180",
    name: "한솔로지스틱스",
    shares: 6791,
    evalAmount: 19320395,
    profit: -679990,
    profitRate: -3.4,
    avgPrice: 2960,
    currentPrice: 2845,
  },
  {
    ticker: "047310",
    name: "파워로직스",
    shares: 3682,
    evalAmount: 16937200,
    profit: -1051100,
    profitRate: -5.84,
    avgPrice: 4900,
    currentPrice: 4600,
  },
  {
    ticker: "230980",
    name: "아이스크림미디어",
    shares: 347,
    evalAmount: 5742850,
    profit: -243160,
    profitRate: -4.06,
    avgPrice: 17260,
    currentPrice: 16550,
  },
  {
    ticker: "000490",
    name: "대동",
    shares: 621,
    evalAmount: 5290920,
    profit: -701990,
    profitRate: -11.71,
    avgPrice: 9680,
    currentPrice: 8520,
  },
];

export const TOTAL_PORTFOLIO = {
  evalAmount: 284098282,
  profit: -50551123,
  profitRate: -15.11,
};

export const MOCK_NEWS = [
  {
    id: 1,
    title: "코스피, 미 관세 효력 항소심 복원에 2,705선 하락… 외국인 2,874억 순매도",
    source: "직썰",
    time: "8분 전",
    category: "시장",
    sentiment: "negative",
    relatedStocks: ["삼성전자", "SK하이닉스"],
  },
  {
    id: 2,
    title: "SK바이오사이언스, 국민성장펀드 3,000억 저리 대출 확정… 폐렴구균백신 임상 3상 가속",
    source: "아시아경제",
    time: "25분 전",
    category: "바이오",
    sentiment: "positive",
    relatedStocks: ["SK바이오사이언스"],
  },
  {
    id: 3,
    title: "대신증권 'SK바이오사이언스 목표주가 56,000원, 적자 지속…임상 결과 2026년 확인'",
    source: "비즈니스포스트",
    time: "52분 전",
    category: "목표가",
    sentiment: "neutral",
    relatedStocks: ["SK바이오사이언스"],
  },
  {
    id: 4,
    title: "삼성전자·SK하이닉스 레버리지 ETF 출시 러시… 코스닥 소부장 이틀 새 10%↓ 투매",
    source: "한국경제TV",
    time: "1시간 전",
    category: "시장",
    sentiment: "negative",
    relatedStocks: ["삼성전자", "SK하이닉스"],
  },
  {
    id: 5,
    title: "한솔로지스틱스, 6월 이커머스 성수기 앞두고 풀필먼트 계약 잇달아 체결",
    source: "서울경제",
    time: "1시간 30분 전",
    category: "물류",
    sentiment: "positive",
    relatedStocks: ["한솔로지스틱스"],
  },
  {
    id: 6,
    title: "파워로직스, 국내 완성차 3사 BMS 신규 공급 계약… 하반기 실적 반등 기대",
    source: "전자신문",
    time: "2시간 전",
    category: "2차전지",
    sentiment: "positive",
    relatedStocks: ["파워로직스"],
  },
  {
    id: 7,
    title: "아이스크림미디어, 2분기 AI 튜터 구독자 전분기 대비 18% 증가… 수익성 개선 주목",
    source: "뉴스1",
    time: "2시간 30분 전",
    category: "에듀테크",
    sentiment: "positive",
    relatedStocks: ["아이스크림미디어"],
  },
  {
    id: 8,
    title: "대동, 북미 스마트농기계 수출 누적 1,000대 돌파… 현지 딜러망 3배 확대 계획",
    source: "농민신문",
    time: "3시간 전",
    category: "농기계",
    sentiment: "positive",
    relatedStocks: ["대동"],
  },
  {
    id: 9,
    title: "원·달러 환율 1,361원 강보합… 외국인 4거래일 연속 순매도·개인 역대 최대 순매수",
    source: "머니투데이",
    time: "4시간 전",
    category: "시장",
    sentiment: "neutral",
    relatedStocks: [],
  },
  {
    id: 10,
    title: "SK하이닉스 HBM4 양산 앞당겨·마이크론 목표가 1,100달러 상향… AI 메모리 슈퍼사이클",
    source: "한국경제",
    time: "5시간 전",
    category: "글로벌",
    sentiment: "positive",
    relatedStocks: ["SK하이닉스"],
  },
];

export const TARGET_PRICE_UPDATES = [
  { stock: "NICE", analyst: "iM증권", before: 13500, after: 11800, date: "2026.05.30", direction: "down" },
  { stock: "SK바이오사이언스", analyst: "대신증권", before: 52000, after: 56000, date: "2026.05.30", direction: "up" },
  { stock: "파워로직스", analyst: "유안타증권", before: 5200, after: 4500, date: "2026.05.29", direction: "down" },
  { stock: "한솔로지스틱스", analyst: "신한투자", before: 3200, after: 3600, date: "2026.05.28", direction: "up" },
  { stock: "대동", analyst: "NH투자증권", before: 10000, after: 11500, date: "2026.05.27", direction: "up" },
];

export const CATEGORIES = ["전체", "매수 원칙", "매수 타이밍", "매수 금지", "매도 원칙", "종목 선정", "계절 주의", "기타"];
